{% set name = "rdma-core" %}
{% set version = "28.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/linux-rdma/rdma-core/archive/v{{ version }}.tar.gz
  sha256: 899761740efc45642ab3bc78e48b73374ce8cd17fcc9155ca44d358a94684b29
  patches:
    - 0001-Remove-assertions-on-longer-than-sockaddr_un.sun_pat.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ cdt("libnl3-devel") }}
    - {{ cdt("systemd-devel") }}
    - cmake
    - ninja
    - libudev
    - libsystemd
    - pandoc

test:
  commands:
    - test -f "${PREFIX}/bin/ibv_devices"
    - ${PREFIX}/bin/ibv_devices

about:
  home: https://github.com/linux-rdma/rdma-core
  license: Linux-OpenIB
  license_family: BSD
  license_file: LICENSE.txt
  summary: RDMA Core Userspace Libraries and Daemons
  doc_url: https://github.com/linux-rdma/rdma-core
  dev_url: https://github.com/linux-rdma/rdma-core

extra:
  recipe-maintainers:
    - pentschev
