{% set name = "rdma-core" %}
{% set version = "51.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/linux-rdma/rdma-core/archive/v{{ version }}.tar.gz
  sha256: 8f641368c6963773a8ea9f9cb1008c8bf5d5c8afd92118c66f17a890f69113fa
  patches:
    - 0001-Remove-assertions-on-longer-than-sockaddr_un.sun_pat.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage("rdma-core", max_pin=None) }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ cdt("systemd-devel") }}
    - cmake
    - ninja
    - libudev
    - libsystemd
    - pandoc
  host:
    - libnl

test:
  commands:
    - test -f "${PREFIX}/bin/ibv_devices"
    # Test `ibv_devices` when building natively
    - ${PREFIX}/bin/ibv_devices            # [build_platform == target_platform]

about:
  home: https://github.com/linux-rdma/rdma-core
  license: Linux-OpenIB
  license_family: BSD
  license_file: LICENSE.txt
  summary: RDMA Core Userspace Libraries and Daemons
  doc_url: https://github.com/linux-rdma/rdma-core
  dev_url: https://github.com/linux-rdma/rdma-core

extra:
  recipe-maintainers:
    - pentschev
